development:
  adapter: postgresql
  encoding: utf8
  database: setfortennis_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: setfortennis_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: setfortennis_production
  pool: 5
  host: localhost
